import { useEffect, useState } from "react";
import { Activity, ArrowRight, LogOut, RefreshCw, ShieldCheck, Users, WalletCards } from "lucide-react";
import { Button, Card, Input } from "../components";

type User={id:string;fullName:string;email:string;phone?:string|null;status:string;createdAt:string};
type Overview={totalUsers:number;activeUsers:number;adminCount:number;transferCounts:Array<{status:string;_count:{_all:number}}>;recentUsers:User[]};

export function Admin(){
 const[me,setMe]=useState<any>(null);const[overview,setOverview]=useState<Overview|null>(null);const[users,setUsers]=useState<User[]>([]);const[error,setError]=useState("");const[loading,setLoading]=useState(true);const[showCreate,setShowCreate]=useState(false);
 const[name,setName]=useState("");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[phone,setPhone]=useState("");
 async function api(path:string,init?:RequestInit){const r=await fetch(path,{credentials:"include",...init});const d=await r.json().catch(()=>({}));if(r.status===401||r.status===403){window.location.href="/auth";throw new Error(d.error||"Administrator access required.");}if(!r.ok)throw new Error(d.error||"Request failed");return d;}
 async function load(){setLoading(true);setError("");try{const [m,o,u]=await Promise.all([api("/api/auth/me"),api("/api/admin/overview"),api("/api/admin/users")]);if(m.user.role!=="ADMIN"){window.location.href="/dashboard";return;}setMe(m.user);setOverview(o);setUsers(u.users);}catch(e){setError(e instanceof Error?e.message:"Could not load admin data");}finally{setLoading(false);}}
 useEffect(()=>{load()},[]);
 async function createUser(e:React.FormEvent){e.preventDefault();setError("");try{await api("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fullName:name,email,password,phone})});setName("");setEmail("");setPassword("");setPhone("");setShowCreate(false);await load();}catch(e){setError(e instanceof Error?e.message:"Could not create user");}}
 async function changeStatus(id:string,status:string){try{await api(`/api/admin/users/${id}/status`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});await load();}catch(e){setError(e instanceof Error?e.message:"Could not update user");}}
 async function logout(){await fetch("/api/auth/logout",{method:"POST",credentials:"include"});window.location.href="/auth";}
 return <div className="min-h-screen bg-wk-paper text-wk-ink">
  <header className="sticky top-0 z-20 border-b border-black/8 bg-wk-paper/90 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><a href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-wk-ink text-sm font-black text-wk-gold">W</span><div><p className="text-lg font-semibold">Wakala</p><p className="text-[10px] font-bold uppercase tracking-[.18em] text-wk-teal">Admin console</p></div></a><div className="flex items-center gap-2"><span className="hidden text-sm text-black/50 sm:block">{me?.email}</span><Button variant="secondary" size="sm" leftIcon={<LogOut size={15}/>} onClick={logout}>Sign out</Button></div></div></header>
  <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
   <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="wk-eyebrow">Operations</p><h1 className="mt-2 text-4xl font-semibold tracking-tight sm:text-5xl">Admin control centre.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-black/50">Manage customers, monitor transfers and keep the Wakala platform operational.</p></div><div className="flex gap-2"><Button variant="secondary" leftIcon={<RefreshCw size={16}/>} onClick={load}>Refresh</Button><Button leftIcon={<Users size={16}/>} onClick={()=>setShowCreate(true)}>Create user</Button></div></div>
   {error&&<div className="mt-6 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
   <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
    <Stat icon={<Users/>} label="Customers" value={overview?.totalUsers??"—"} note={`${overview?.activeUsers??0} active`}/>
    <Stat icon={<Activity/>} label="Transfers" value={overview?.transferCounts.reduce((a,x)=>a+x._count._all,0)??"—"} note="All statuses"/>
    <Stat icon={<ShieldCheck/>} label="Administrators" value={overview?.adminCount??"—"} note="Privileged accounts"/>
    <Stat icon={<WalletCards/>} label="System" value={loading?"Loading":"Online"} note="API + database"/>
   </section>
   <div className="mt-8 grid gap-6 lg:grid-cols-[1.35fr_.65fr]">
    <Card className="overflow-hidden p-0"><div className="flex items-center justify-between border-b border-black/6 px-5 py-4"><div><h2 className="font-semibold">Customers</h2><p className="text-xs text-black/40">Up to 100 most recent accounts</p></div><span className="rounded-full bg-wk-teal/10 px-3 py-1 text-xs font-bold text-wk-teal">{users.length} loaded</span></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-black/[.025] text-xs uppercase tracking-wider text-black/40"><tr><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Wallets</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t border-black/5"><td className="px-5 py-4"><p className="font-semibold">{u.fullName}</p><p className="text-xs text-black/40">{u.email}</p></td><td className="px-5 py-4 text-xs text-black/55">{u.wallets?.map((w:any)=>w.currency).join(" · ")||"No wallet"}</td><td className="px-5 py-4"><span className={"rounded-full px-2.5 py-1 text-xs font-bold "+(u.status==="ACTIVE"?"bg-wk-teal/10 text-wk-teal":"bg-black/5 text-black/50")}>{u.status}</span></td><td className="px-5 py-4 text-right"><select value={u.status} onChange={e=>changeStatus(u.id,e.target.value)} className="rounded-xl border border-black/10 bg-white px-3 py-2 text-xs font-semibold"><option>ACTIVE</option><option>SUSPENDED</option><option>CLOSED</option></select></td></tr>)}{!users.length&&!loading&&<tr><td colSpan={4} className="px-5 py-12 text-center text-sm text-black/40">No customers yet.</td></tr>}</tbody></table></div></Card>
    <Card><p className="wk-eyebrow">Recent activity</p><h2 className="mt-2 text-xl font-semibold">New customers</h2><div className="mt-5 space-y-4">{(overview?.recentUsers??[]).map(u=><div key={u.id} className="flex items-center gap-3 border-b border-black/6 pb-4"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-wk-ink text-xs font-bold text-white">{u.fullName.slice(0,1).toUpperCase()}</div><div className="min-w-0"><p className="truncate text-sm font-semibold">{u.fullName}</p><p className="truncate text-xs text-black/40">{u.email}</p></div></div>)}</div></Card>
   </div>
  </main>
  {showCreate&&<div className="fixed inset-0 z-50 grid place-items-center bg-wk-ink/50 p-4" onMouseDown={e=>e.target===e.currentTarget&&setShowCreate(false)}><Card className="w-full max-w-lg"><div className="flex items-center justify-between"><div><p className="wk-eyebrow">Customer onboarding</p><h2 className="mt-1 text-2xl font-semibold">Create a user</h2></div><button className="rounded-xl px-3 py-2 text-black/40 hover:bg-black/5" onClick={()=>setShowCreate(false)}>✕</button></div><form className="mt-6 space-y-4" onSubmit={createUser}><Input label="Full name" value={name} onChange={e=>setName(e.target.value)} required/><Input label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><Input label="Phone" value={phone} onChange={e=>setPhone(e.target.value)}/><Input label="Temporary password" type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} required/><Button type="submit" size="lg" className="w-full" rightIcon={<ArrowRight size={17}/>}>Create customer</Button></form></Card></div>}
 </div>
}
function Stat({icon,label,value,note}:{icon:React.ReactNode;label:string;value:any;note:string}){return <Card className="p-5"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-wk-teal/10 text-wk-teal">{icon}</span><span className="text-[10px] font-bold uppercase tracking-wider text-black/30">{label}</span></div><p className="mt-6 text-3xl font-semibold">{value}</p><p className="mt-1 text-xs text-black/40">{note}</p></Card>}
