import { ArrowRight, Send, Plus, Smartphone, ArrowUpRight, ArrowDownLeft, MoreHorizontal, Globe2, CreditCard } from "lucide-react";\nimport type { ReactNode } from "react";
import { BalanceCard, Button, Card, TransactionList, PageHeader, type TransactionRowProps } from "../components";
const transactions:TransactionRowProps[]=[{title:"Wallet top up",description:"Today · Bank transfer",amount:250000,currency:"NGN",status:"completed",type:"deposit"},{title:"Transfer to Amina",description:"Yesterday · Bank transfer",amount:-45000,currency:"NGN",status:"completed",type:"transfer"},{title:"eSIM purchase",description:"Sep 24 · Connectivity",amount:-18500,currency:"NGN",status:"processing",type:"card"}];
export function Dashboard(){return <><PageHeader title="Good morning, Dre" description="Here is what is happening with your Wakala account today." actions={<Button variant="success" size="lg" leftIcon={<Send size={17}/>} onClick={()=>window.location.href="/transfer"}>Transfer money</Button>}/>
<div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><BalanceCard amount={2864500} currency="NGN" available={2814500} pending={50000}/><Card className="bg-wk-ink text-white"><div className="flex items-start justify-between"><div><p className="text-xs text-white/45">Quick action</p><h2 className="mt-2 text-xl font-semibold">Move money</h2></div><Send className="text-wk-gold"/></div><p className="mt-3 text-sm leading-6 text-white/45">Send money to a bank account or another supported recipient.</p><Button className="mt-6 w-full bg-white text-wk-ink hover:bg-white/90" rightIcon={<ArrowRight size={16}/>} onClick={()=>window.location.href="/transfer"}>Start a transfer</Button></Card></div>
<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={<ArrowUpRight size={18}/>} label="Money in" value="₦250,000" meta="Today"/><Stat icon={<ArrowDownLeft size={18}/>} label="Money out" value="₦63,500" meta="This week"/><Stat icon={<Globe2 size={18}/>} label="Coverage" value="4 markets" meta="Regional vision"/><Stat icon={<CreditCard size={18}/>} label="Cards" value="1 active" meta="Coming soon"/></div>
<div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><TransactionList transactions={transactions} onViewAll={()=>{}}/><Card><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-wk-teal">Connectivity</p><h2 className="mt-2 text-xl font-semibold">Wakala eSIM</h2></div><Smartphone className="text-wk-teal"/></div><div className="mt-7 rounded-2xl bg-wk-paper p-5"><p className="text-sm font-semibold">Stay connected across borders</p><p className="mt-2 text-xs leading-5 text-black/45">Regional eSIM packages are being prepared for the Wakala app.</p><div className="mt-5 flex flex-wrap gap-2">{["NG","KE","RW","TZ"].map(c=><span key={c} className="rounded-lg bg-white px-3 py-2 text-xs font-bold">{c}</span>)}</div></div><Button variant="secondary" className="mt-4 w-full" rightIcon={<ArrowRight size={16}/>}>Explore eSIM</Button></Card></div>
<div className="mt-5 grid gap-4 sm:grid-cols-3"><Action icon={<Plus/>} title="Add money" text="Fund your wallet"/><Action icon={<Send/>} title="Send money" text="Make a transfer"/><Action icon={<MoreHorizontal/>} title="More services" text="Explore Wakala"/></div></>}
function Stat({icon,label,value,meta}:{icon:ReactNode;label:string;value:string;meta:string}){return <Card className="p-5"><div className="flex items-center justify-between"><span className="grid h-9 w-9 place-items-center rounded-xl bg-wk-teal/10 text-wk-teal">{icon}</span><span className="text-[11px] text-black/35">{meta}</span></div><p className="mt-5 text-xs text-black/45">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></Card>}
function Action({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <button className="flex items-center gap-4 rounded-2xl border border-black/7 bg-white p-5 text-left transition hover:-translate-y-0.5 hover:shadow-lg"><span className="grid h-11 w-11 place-items-center rounded-xl bg-wk-ink text-wk-gold">{icon}</span><span><span className="block text-sm font-bold">{title}</span><span className="mt-1 block text-xs text-black/40">{text}</span></span><ArrowRight className="ml-auto text-black/25" size={17}/></button>}