import { ArrowRight, Globe2, MapPin, Smartphone, WalletCards } from "lucide-react";
export function OldWakalaHome(){
 const nodes=[["Tanzania","TZS","18%","27%"],["Kenya","KES","79%","23%"],["Rwanda","RWF","14%","61%"],["Zanzibar","TZS","83%","61%"],["Nigeria","NGN","24%","78%"],["Global","USD","71%","79%"]];
 return <div className="old-wakala"><header className="old-nav"><a className="old-brand" href="/"><span/>WAKALA</a><nav><a href="#network">Network</a><a href="#how">How it works</a><a href="#coverage">Coverage</a><a href="#wallet">Wallet + eSIM</a></nav><div className="old-actions"><a href="/auth">Sign in</a><a className="old-pill" href="/auth">Open your wallet <ArrowRight size={15}/></a></div></header>
 <main><section className="old-hero"><div className="old-hero-copy"><p className="old-eyebrow">A payment rail for a connected Africa</p><h1>Pay in your own <em>local currency.</em></h1><p className="old-lead">Wakala connects local currencies, wallets and payment methods so money can move with less friction across the markets you call home.</p><div className="old-hero-buttons"><a className="old-primary" href="/auth">Open your wallet <ArrowRight size={16}/></a><a className="old-secondary" href="#network">Explore the network</a></div><p className="old-note">Local-currency first · Built for everyday cross-border movement</p></div><div className="old-network-wrap"><div className="old-network" id="network"><div className="old-grid"/><svg viewBox="0 0 680 680" aria-hidden="true"><path d="M135 210 C230 165 340 340 525 180"/><path d="M120 420 C270 540 440 540 560 400"/><path d="M190 120 C110 260 120 390 200 540"/><path d="M480 120 C570 250 570 410 470 550"/></svg><div className="old-orbit"/><div className="old-core"><strong>WAKALA</strong><span>DIRECT RAIL</span></div>{nodes.map(([name,currency,left,top])=><div key={name} className="old-node" style={{left,top}}><i/><b>{name}</b><small>{currency}</small></div>)}<div className="old-flow f1"/><div className="old-flow f2"/><div className="old-flow f3"/><div className="old-live"><span>LIVE TRANSFER</span><b>+ TZS 840,000</b><small>Tanzania → Kenya · just now</small></div></div></div></section>
 <div className="old-ticker"><span>LOCAL CURRENCY FIRST</span><span>WALLETS</span><span>TRANSFERS</span><span>eSIM CONNECTIVITY</span><span>NIGERIA · KENYA · RWANDA · TANZANIA · ZANZIBAR</span><span>LOCAL CURRENCY FIRST</span></div>
 <section className="old-section old-problem"><div className="old-container old-two"><div><p className="old-eyebrow">The problem</p><h2>Money should move as naturally as people do.</h2><p className="old-muted">Cross-border payments can feel like a chain of accounts, conversions and disconnected services. Wakala brings the experience into one place.</p></div><div className="old-list"><div><b>01</b><span>Hold and manage multiple currencies.</span></div><div><b>02</b><span>Move money across supported markets.</span></div><div><b>03</b><span>Stay connected with travel eSIM services.</span></div></div></div></section>
 <section className="old-section" id="how"><div className="old-container"><div className="old-section-head"><p className="old-eyebrow">How it works</p><h2>One experience from wallet to movement.</h2></div><div className="old-cards"><article><span>01</span><WalletCards/><h3>Create your wallet</h3><p>Set up one Wakala account and keep your supported currencies together.</p></article><article><span>02</span><Globe2/><h3>Move across markets</h3><p>Choose the currency and destination that fits the transaction you need to make.</p></article><article><span>03</span><Smartphone/><h3>Stay connected</h3><p>Use Wakala eSIM connectivity as you travel between supported markets.</p></article></div></div></section>
 <section className="old-section old-coverage" id="coverage"><div className="old-container"><p className="old-eyebrow">Regional coverage</p><h2>Built around the corridors people actually use.</h2><div className="old-country-grid">{["Nigeria · NGN","Kenya · KES","Rwanda · RWF","Tanzania · TZS","Zanzibar · TZS"].map(x=><div key={x}><MapPin size={16}/><b>{x}</b><span>Supported market</span></div>)}</div></div></section>
 <section className="old-section old-wallet" id="wallet"><div className="old-container old-two"><div><p className="old-eyebrow">Wallet + connectivity</p><h2>One wallet. More ways to move.</h2><p className="old-muted">The Wakala experience brings balance visibility, transfers and connectivity into a single product language.</p><a className="old-primary" href="/auth">Get started <ArrowRight size={16}/></a></div><div className="old-phone"><div className="old-phone-screen"><span>WAKALA</span><strong>USD 4,280.00</strong><small>Available balance</small><div/><p>+ TZS 840,000 <em>Completed</em></p><p>− KES 18,500 <em>Completed</em></p></div></div></div></section>
 </main><footer className="old-footer"><div className="old-container"><span className="old-brand"><span/>WAKALA</span><p>Pay in your own currency, anywhere.</p></div></footer></div>
}