import type { ReactNode } from "react";
import { Menu, X, Bell, HelpCircle, LogOut, ChevronRight } from "lucide-react";
import { useState } from "react";
import { Button } from "../ui/Button";
export type NavItem={label:string;href:string;icon?:ReactNode};
export function AppShell({children,navItems,active="Dashboard",brand="wakala",userName="User"}:{children:ReactNode;navItems:NavItem[];active?:string;brand?:string;userName?:string}){
 const[open,setOpen]=useState(false);
 return <div className="min-h-screen bg-wk-paper text-wk-ink">
  <aside className="fixed inset-y-0 left-0 z-40 hidden w-64 border-r border-black/5 bg-white px-4 py-5 lg:flex lg:flex-col"><Brand name={brand}/><Sidebar items={navItems} active={active}/><div className="mt-auto"><div className="mb-3 rounded-2xl bg-wk-teal/8 p-4"><p className="text-xs font-bold text-wk-teal">Need help?</p><p className="mt-1 text-xs leading-5 text-black/45">Get support with your account or transfers.</p><a href="#" className="mt-3 inline-flex items-center gap-1 text-xs font-bold">Support <ChevronRight size={13}/></a></div><div className="rounded-2xl bg-wk-ink p-4 text-white"><p className="text-xs text-white/40">Signed in as</p><p className="mt-1 truncate text-sm font-semibold">{userName}</p></div></div></aside>
  <div className="lg:pl-64"><header className="sticky top-0 z-30 flex h-[72px] items-center justify-between border-b border-black/5 bg-wk-paper/90 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><button className="rounded-xl p-2 lg:hidden" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu size={21}/></button><div className="hidden lg:block"><p className="text-xs text-black/35">Wakala account</p><p className="text-sm font-bold">{active}</p></div><div className="flex items-center gap-2"><button className="grid h-10 w-10 place-items-center rounded-xl border border-black/8 bg-white text-black/55 hover:bg-black/[.03]" aria-label="Help"><HelpCircle size={18}/></button><button className="relative grid h-10 w-10 place-items-center rounded-xl border border-black/8 bg-white text-black/55" aria-label="Notifications"><Bell size={18}/><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-wk-teal"/></button><div className="ml-1 grid h-10 w-10 place-items-center rounded-full bg-wk-ink text-sm font-bold text-white">{userName.slice(0,1).toUpperCase()}</div></div></header><main className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8">{children}</main></div>
  {open&&<div className="fixed inset-0 z-50 bg-wk-ink/40 lg:hidden" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><aside className="flex h-full w-[min(88vw,330px)] flex-col bg-white p-4 shadow-2xl"><div className="flex items-center justify-between"><Brand name={brand}/><button className="rounded-xl p-2" onClick={()=>setOpen(false)} aria-label="Close navigation"><X/></button></div><div className="mt-7"><Sidebar items={navItems} active={active} onNavigate={()=>setOpen(false)}/></div><div className="mt-auto border-t border-black/5 pt-4"><a href="/auth" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-black/55"><LogOut size={17}/> Sign out</a></div></aside></div>}
 </div>
}
function Brand({name}:{name:string}){return <a href="/" className="flex items-center gap-3 px-2"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-wk-ink text-sm font-black text-wk-gold">W</span><span className="text-xl font-semibold tracking-tight">{name}</span></a>}
function Sidebar({items,active,onNavigate}:{items:NavItem[];active:string;onNavigate?:()=>void}){return <nav className="mt-8 space-y-1" aria-label="Application navigation">{items.map(item=><a key={item.label} href={item.href} onClick={onNavigate} className={"flex items-center gap-3 rounded-2xl px-3 py-3 text-sm font-semibold transition "+(active===item.label?"bg-wk-ink text-white shadow-sm":"text-black/55 hover:bg-black/[.04] hover:text-wk-ink")}>{item.icon}<span>{item.label}</span></a>)}</nav>}